### PR TITLE
Cmake support examples

### PR DESCRIPTION
**Pull request by stefanschober**
The following examples are enhanced with `cmake` support:
- [Posix/Win32 dpp example](https://github.com/stefanschober/qpc-examples/tree/cmakeSupport/posix-win32/dpp)
- [QWin GUI dpp example](https://github.com/stefanschober/qpc-examples/tree/cmakeSupport/qwin-gui/dpp-gui)

This [Posix/Win32 cmake example](https://github.com/stefanschober/qpc-examples/tree/cmakeSupport/posix-win32-cmake/dpp) is a full featured example, which shows how to use `cmake`with qpc to automatically generate build systems for different platforms and configurations.

Another [example](https://github.com/stefanschober/TrafficLight), a simple trafficlight simulation, shows how to set up a system with various BSPs for different target systems and use `cmake` to build them with the matching cross compilers from one combined source code repository.

### CODE REVIEW

**Comment by quantum-leaps** [comment]
Hi Stefan,
I've manually merged the qpc-examples, but due to the recent changes, the posix-win32-cmake does not build. Specifically, the "presets" dpp and mingw need the QP_CONFIG macro defined. I was not sure where to put that.
--MMS

**Comment by stefanschober** [comment]
Hi Miro,

after having a deeper look into this topic, I decided to change the
strategy concerning the handling of 'qp_config.h'.
As your examples show, the intention behind 'qp_config.h' is to be a
project specific configuration. The file itself shall therefore
reside outside of the qpc source tree.

Based on this I reworked the repos for qpc, qpc-examples and 3rd-party with
the following updates:
* 3rd-party: the default URL for automatic download of qpc now points to
QuantumLeap's github repo
* qpc-examples: the example posix-win32-cmake/dpp shows one possibility to
integrate 'qp_config.h'
* qpc: the config variables mentioned above are removed

I hope this better fits into the overall setup and strategy of qpc.

Thanks for the great work you did with providing this framework to the
world :)


Best regards
Stefan

-- 
Stefan Schober
Tuttlingen, Germany
***@***.***


Am Sa., 17. Feb. 2024 um 02:44 Uhr schrieb MMS ***@***.***>:

**Comment by quantum-leaps** [comment]
Your latest changes have been manually merged in.
--MMS

**Comment by stefanschober** [comment]
proposed changes are merged into the main branch.
closed

**Pull request closed without merging**
